# Config file - major
FOLDER_STARTUP = "FOLDER_STARTUP"
FOLDER_LOG = "FOLDER_LOG"

# process related
PROC_MAX_NUM = "PROC_MAX_NUM"
PROC_SLEEP_DELAY = "PROC_SLEEP_DELAY"
PROC_THREAD_SLEEP_DELAY = "PROC_THREAD_SLEEP_DELAY"
PROC_FILE_TIMEOUT = "PROC_FILE_TIMEOUT"
PROC_FILE_ROTATE = "PROC_FILE_ROTATE"
PROC_FILE_FLIP = "PROC_FILE_FLIP"
PROC_FILE_CONVERSION_TYPE = "PROC_FILE_CONVERSION_TYPE"
PROC_FILE_TEST_MOD_TIME = "PROC_FILE_TEST_EXISTS"
PROC_FILE_TEST_SIZE = "PROC_FILE_TEST_SIZE"
PROC_PATH_REPLACE = "PROC_PATH_REPLACE"


# logging
LOGGING_MAIN_FILE = "LOGGING_MAIN_FILE"
LOGGING_MAIN_FORMAT = "LOGGING_MAIN_FORMAT"
LOGGING_MAIN_DATE = "LOGGING_MAIN_DATE"
LOGGING_FILE_FORMAT = "LOGGING_FILE_FORMAT"
LOGGING_FILE_DATE = "LOGGING_FILE_DATE"